// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_hello = NULL;
lv_obj_t *ui_Name1 = NULL;
lv_obj_t *ui_aiclub = NULL;
lv_obj_t *ui_Container1 = NULL;
lv_obj_t *ui_Container2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x06073B),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image1 = lv_image_create(ui_Screen1);
  lv_image_set_src(ui_Image1, &ui_img_1147937936);
  lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 130
  lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 130
  lv_obj_set_x(ui_Image1, -105);
  lv_obj_set_y(ui_Image1, 75);
  lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
  lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_hello = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_hello, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_hello, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_hello, -6);
  lv_obj_set_y(ui_hello, -28);
  lv_obj_set_align(ui_hello, LV_ALIGN_CENTER);
  lv_label_set_text(ui_hello, "Hello! My name is");
  lv_obj_set_style_text_color(ui_hello, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_hello, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_decor(ui_hello, LV_TEXT_DECOR_NONE,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_hello, &ui_font_Font1,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_hello, LV_GRAD_DIR_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Name1 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Name1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Name1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Name1, 4);
  lv_obj_set_y(ui_Name1, 0);
  lv_obj_set_align(ui_Name1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Name1, "Kevin Petrov");
  lv_obj_set_style_text_color(ui_Name1, lv_color_hex(0xCEFF00),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Name1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_decor(ui_Name1, LV_TEXT_DECOR_NONE,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Name1, &ui_font_arcadename,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_Name1, LV_GRAD_DIR_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_aiclub = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_aiclub, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_aiclub, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_aiclub, 31);
  lv_obj_set_y(ui_aiclub, 74);
  lv_obj_set_align(ui_aiclub, LV_ALIGN_CENTER);
  lv_label_set_text(ui_aiclub, "King's AI SEMINAR");
  lv_obj_set_style_text_color(ui_aiclub, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_aiclub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_decor(ui_aiclub, LV_TEXT_DECOR_NONE,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_aiclub, &ui_font_Font1,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_dir(ui_aiclub, LV_GRAD_DIR_NONE,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container1 = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_Container1);
  lv_obj_set_width(ui_Container1, 258);
  lv_obj_set_height(ui_Container1, -67);
  lv_obj_set_x(ui_Container1, 3);
  lv_obj_set_y(ui_Container1, 100);
  lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_Container1,
                     LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_color(ui_Container1, lv_color_hex(0xFFFFFF),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0xFFFFFF),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Container1, 255,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Container1, 1,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Container1, 0,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF),
                            LV_PART_SCROLLBAR | LV_STATE_PRESSED);
  lv_obj_set_style_bg_opa(ui_Container1, 255,
                          LV_PART_SCROLLBAR | LV_STATE_PRESSED);

  ui_Container2 = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_Container2);
  lv_obj_set_width(ui_Container2, 258);
  lv_obj_set_height(ui_Container2, -67);
  lv_obj_set_x(ui_Container2, 1);
  lv_obj_set_y(ui_Container2, 49);
  lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_Container2,
                     LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_color(ui_Container2, lv_color_hex(0xFFFFFF),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_Container2, lv_color_hex(0xFFFFFF),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Container2, 255,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Container2, 1,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Container2, 0,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF),
                            LV_PART_SCROLLBAR | LV_STATE_PRESSED);
  lv_obj_set_style_bg_opa(ui_Container2, 255,
                          LV_PART_SCROLLBAR | LV_STATE_PRESSED);
}

void ui_Screen1_screen_destroy(void) {
  if (ui_Screen1)
    lv_obj_del(ui_Screen1);

  // NULL screen variables
  ui_Screen1 = NULL;
  ui_Image1 = NULL;
  ui_hello = NULL;
  ui_Name1 = NULL;
  ui_aiclub = NULL;
  ui_Container1 = NULL;
  ui_Container2 = NULL;
}
